<?php

namespace app\modules\admin\controllers;

use app\models\LoginForm;
use app\models\User;
use yii\filters\AccessControl;
use yii\web\Controller;

/**
 * Default controller for the `admin` module
 */
class BaseController extends Controller
{
    public $layout = 'main';

    public function beforeAction($action)
    {

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

}
