<?php

namespace app\modules\admin\controllers;

use app\components\Helper;
use app\constants\AppConstants;
use app\models\Category;
use app\models\City;
use app\models\Contact;
use app\models\Discount;
use app\models\Image;
use app\models\Schedule;
use app\modules\admin\components\AccessRule;
use app\modules\admin\components\DeleteAction;
use app\modules\admin\models\search\CategorySearch;
use app\modules\admin\models\search\CitySearch;
use app\modules\admin\models\search\ContactSearch;
use app\modules\admin\models\search\DiscountSearch;
use Yii;
use app\models\User;
use app\modules\admin\models\search\UserSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UsersController implements the CRUD actions for User model.
 */
class ContactsController extends BaseController
{
    protected function getClassName()
    {
        return Contact::className(); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        $rules = parent::behaviors();
        return $rules;
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex($place_id)
    {
        $searchModel = new ContactSearch();
        $params['ContactSearch']['place_id'] = $place_id;
        $dataProvider = $searchModel->search($params);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'isCanAdd' => Contact::isCanAddMore($place_id)
        ]);
    }

    public function actionCreate($place_id)
    {
        $this->isCanAddMore($place_id);
        $model = new Contact();
        $model->place_id = (int)$place_id;

        if ($model->load(Yii::$app->request->post())) {
            if ($model->save()) {
                return $this->redirect(['index', 'place_id' => $model->place_id]);
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionUpdate($id)
    {
        $model = Contact::findOneModel($id);
        $this->isCanAddMore($model->place_id);

        if ($post = Yii::$app->request->post()) {
            /** @var Discount $newModel */
            $newModel = $model->getDuplicate();
            if ($newModel->load(Yii::$app->request->post()) && $newModel->save()) {

                if (isset($post['copy'])) {
                    return $this->redirect(['copy-to-parent', 'id' => $id]);
                }

                Helper::setMessage('Изменения сохранены, ожидают проверки', Helper::TYPE_MESSAGE_SUCCESS);

                return $this->redirect(['index', 'place_id' => $newModel->place_id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);

    }

}