<?php

namespace app\modules\admin\controllers;

use app\constants\AppConstants;
use app\constants\ImageConstants;
use app\models\Category;
use app\models\City;
use app\models\Discount;
use app\models\Image;
use app\models\Schedule;
use app\models\traits\ImageUploaderController;
use app\modules\admin\components\AccessRule;
use app\modules\admin\components\DeleteAction;
use app\modules\admin\models\search\CategorySearch;
use app\modules\admin\models\search\CitySearch;
use app\modules\admin\models\search\DiscountSearch;
use Yii;
use app\models\User;
use app\modules\admin\models\search\UserSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UsersController implements the CRUD actions for User model.
 */
class DiscountsController extends BaseController
{
    use ImageUploaderController;

    public function getScenario()
    {
        return ImageConstants::SCENARIO['MAIN_DISCOUNT'];
    }

    public function getPrefix()
    {
        return ImageConstants::IMAGE_SIZE['MAIN_DISCOUNT'][0];
    }

    protected function getClassName()
    {
        return Discount::className(); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        $rules = parent::behaviors();
        $rules['access']['rules'][] = [
            'actions' => ['upload-image'],
            'allow' => true,
            'roles' => ['?'],
        ];

        return $rules;
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex($place_id)
    {
        $searchModel = new DiscountSearch();
        $params = Yii::$app->request->queryParams;
        $params['DiscountSearch']['place_id'] = $place_id;
        $dataProvider = $searchModel->search($params);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'isCanAdd' => Discount::isCanAddMore($place_id)
        ]);
    }

    public function actionCreate($place_id)
    {
        $this->isCanAddMore($place_id);
        $model = new Discount();
        $model->place_id = (int)$place_id;

        if ($model->load(Yii::$app->request->post())) {
            if ($model->save()) {
                $model->uploadNewImageByUrl(Yii::$app->request->post('images'), ImageConstants::TYPE['MAIN_DISCOUNT']);
                return $this->redirect(['index', 'place_id' => $model->place_id]);
            }
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    public function actionUpdate($id)
    {
        $model = Discount::findOne($id);
        $this->isCanAddMore($model->place_id);
        if ($post = Yii::$app->request->post()) {
            /** @var Discount $newModel */
            $newModel = $model->getDuplicate();
            if ($newModel->load(Yii::$app->request->post()) && $newModel->save()) {
                $newModel->uploadNewImageByUrl(
                    array_merge(explode(',',$post['old_images']),explode(',',$post['images'])),
                    ImageConstants::TYPE['MAIN_DISCOUNT']);
                return $this->redirect(['index', 'place_id' => $newModel->place_id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);

    }

}