<?php

namespace app\controllers;

use app\components\Geo;
use yii\web\Controller;

class BaseMapController extends Controller
{
    public function beforeAction($action)
    {
        if (!isset($_COOKIE['lat']) || !isset($_COOKIE['lon'])) {
            $coords = Geo::getUserLatLon();
            Geo::setUserLatLon($coords);
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}
