<?php

namespace app\components\file;

use app\constants\ImageConstants;

class ImageDiscountMain extends FileHandler
{

    public static function createThumbs($url)
    {
        parent::createThumbs($url); // TODO: Change the autogenerated stub
    }

    protected static function getSizes()
    {
        return [
            ImageConstants::IMAGE_SIZE['DISCOUNT']
        ];
    }

    public static function deleteFiles($url)
    {
        parent::deleteFiles($url); // TODO: Change the autogenerated stub
    }
}