<?php

namespace app\components\file;

use app\constants\ImageConstants;

class ImageMainHandler extends FileHandler
{
    protected static function getSizes()
    {
        return [
            ImageConstants::IMAGE_SIZE['MAP']
        ];
    }

    public static function deleteFiles($url)
    {
        parent::deleteFiles($url); // TODO: Change the autogenerated stub
    }
}