<?php

namespace app\models;

use app\components\file\FileHelper;
use app\components\file\ImagePlaceHandler;
use app\components\SiteException;
use app\constants\AppConstants;
use app\constants\ImageConstants;
use yii\behaviors\TimestampBehavior;



class BaseSubPlacesModel extends BaseModel implements ISubPlaces
{
    public static function isCanAdd($place_id) {
        $class = static::className();
        $count = $class::find()->andWhere(['place_id' => (int)$place_id, 'status' => AppConstants::STATUS['NO_MODERATE']])->count();
        return $count < 5;
    }

    public function isUpdatable() {
        if ($this->hasAttribute('place_id')) {
            return self::isCanAdd($this->place_id);
        }
        return false;
    }

    public function beforeSave($insert)
    {
        if ($insert) {
            if ($this->hasAttribute('ip')) {
                $this->ip = ip2long($_SERVER['REMOTE_ADDR']);
            }
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}
