<?php

namespace app\models;

use Imagine\Image\Box;
use Imagine\Image\ImageInterface;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "{{%image}}".
 *
 * @property integer id
 * @property integer place_id
 * @property string url
 * @property string description
 * @property integer status
 * @property integer type
 * @property integer created_at
 */

class Image extends \yii\db\ActiveRecord
{
    public $image;

    const STATUS_NO_MODERATE = 0;
    const STATUS_MODERATE = 1;

    const TYPE_MAIN = 0;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%image}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['place_id', 'url'], 'required'],
            [['place_id', 'status', 'type', 'created_at'], 'number'],
            //[['url'], 'string', 'max' => 100],
            [['description'], 'string', 'max' => 255],
            [['url'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg', 'maxSize' => 1024 * 1024 * 2, 'tooBig' => 'Максимум 2MB'],

        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'place_id' => 'Место',
            'status' => 'Статус',
            'type' => 'Тип',
            'url' => 'Путь',
            'description' => 'Описание',
            'created_at' => 'Дата создания',
        ];
    }

    public function beforeDelete()
    {
        $this->deleteImage();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }


    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'updatedAtAttribute' => false
            ]
        ];
    }

    public static function getStatusesMap()
    {
        return [
            self::STATUS_NO_MODERATE => 'Не проверено',
            self::STATUS_MODERATE => 'Проверено'
        ];
    }

    public function upload(Place $place)
    {
        $this->place_id = $place->getId();

        $url = $place->getDir() . '/' . uniqid() . '.' . $this->url->extension;
        $url1 = $place->getDir() . '/thumb_' . uniqid() . '.' . $this->url->extension;

        if ($this->validate()) {
            $this->url->saveAs($url);
            $options = array(
                'quality' => 100,
                'jpeg_quality' => 100,
            );

            \yii\imagine\Image::getImagine()->open($url)->thumbnail(new Box(200, 150))->save($url1, $options);
            //\yii\imagine\Image::thumbnail($url, 120, 120)->save($url1, ['quality' => 100]);
            $this->url = $url;
            return true;
        }

        return false;
    }

    public static function findByPlaceId($place_id)
    {
        return self::find()->andWhere('place_id = :place_id',[':place_id' => $place_id]);
    }


    public function deleteImage()
    {
        $url = \Yii::getAlias('@webroot') . '/' . $this->getUrl();
        if (file_exists($url) && is_file($url)) {
            unlink($url);
            return true;
        }
        return false;
    }

    public function getPlace()
    {
        return $this->hasOne(Place::className(), ['id' => 'place_id']);
    }

    public function getUrl() {
        return $this->url;
    }

    public function getId() {
        return $this->id;
    }

    public function getImageUrl() {
        return '/' . $this->getUrl();
    }
}
